name: Update README
on:
  schedule:
    - cron: '0 0 * * *' # S'exécute tous les jours à minuit
  workflow_dispatch: # Permet de lancer manuellement depuis l'interface GitHub
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v3
      - name: Installation de Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Exécution du script
        run: node index.js
      - name: Commit et Push des changements
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m "docs: mise à jour automatique du README" || exit 0
          git push